### ISSUE TITLE
loss反向传播报错

### ISSUE THREAD

**Issue by hhr114** [thuml/Koopa#1]
torch版本：1.10.0+cu113
报错信息：`NotImplementedError: the derivative for 'linalg_lstsq' is not implemented.`
出错位置：https://github.com/thuml/Koopa/blob/34b6cd9895d6d4bfe778c20036557b4989025935/models/Koopa.py#L80
运行命令：`python3 run.py --dynamic_dim=256 --hidden_dim=512 --seq_len=32 --seg_len=16 --hidden_layers=3 --num_blocks=3 --des='Exp' --model=Koopa --cache_dir=rawData_5M_sl32 --debug --learning_rate=1e-3 --test_bs=2048`
![image.png](https://fc.sinaimg.cn/large/9760198agy1hj0ltvgsqrj20ko030dhw.jpg)

**Comment by WenWeiTHU** [comment]
您好，可以尝试更高的1.12及以上的torch版本
