### ISSUE TITLE
Can Koopa model works on 2D datasets? Such as human trajectories? e.g. (x, y)

### ISSUE THREAD

**Issue by Carrotsniper** [thuml/Koopa#11]

**Comment by lichenyu20** [comment]
Koopa does not naturally support 2D datasets forecasting.
If you are going to use Koopa to forecast 2D points in the form (x,y), you could treat 2D points as multivariate data. You could preprocess the 2D datasets in the form of multivariate data with the shape (L, 2).

**Comment by Carrotsniper** [comment]
> Koopa does not naturally support 2D datasets forecasting. If you are going to use Koopa to forecast 2D points in the form (x,y), you could treat 2D points as multivariate data. You could preprocess the 2D datasets in the form of multivariate data with the shape (L, 2).

Thanks for your very quick reply, thats very helpful.
I will go have a try.
