### ISSUE TITLE
能适用于短时高维的时间序列吗

### ISSUE THREAD

**Issue by xiatian815** [thuml/Koopa#12]
利用koopman理论有限维逼近无限维，可以处理高维度的时间序列，看到作者提出的算子适应适合长期预测，不知道是否适用于短期预测呢？

**Comment by WenWeiTHU** [comment]
您好，感谢关注。有关短期预测，论文中Table.2使用的M4数据集[1]是一个典型的短期预测数据集，所提出的Koopa模型在其上取得了最优的效果，证明了该模型在的短期预测任务的适用性。

另外，关于高维时间序列（或称多变量时间序列），推荐您关注我们另一篇工作[iTransformer](https://github.com/thuml/iTransformer/tree/main)。


[1] The M4 Competition: 100,000 time series and 61 forecasting methods.
