### ISSUE TITLE
Purpose to set pred_len=1 in KPLayer?

### ISSUE THREAD

**Issue by Carrotsniper** [thuml/Koopa#13]
Thanks for your amazing work!
I don't quite understand why you set pred_len=1 in 
**https://github.com/thuml/Koopa/blob/main/models/Koopa.py#L92**.

I am running experiments on "ETTh2_96_48".

**Comment by WenWeiTHU** [comment]
Hello, it is just the default value. In fact, ```pred_len``` means the step (not the length) that the dynamical system advances forward.
