### ISSUE TITLE
Degree of Variation Experiment

### ISSUE THREAD

**Issue by khan-yin** [thuml/Koopa#15]
Hello Author，I am curious about two component features after Fourier Filter, can you tell me the details or show me the code  how you did the visualization study on features and how can I calculate Degree of Variation

**Comment by lichenyu20** [comment]
Hello, you can calculate Degree of Variation as follows:
1. decompose the series into time-invariant component and time-variant component;
2. utilize the two components to train MLPs;
3. calculate the standard deviation of linear weighting.
