### ISSUE TITLE
FFT - BUG

### ISSUE THREAD

**Issue by MuliMuri** [thuml/Koopa#17]
Dear author,
In your code, I found a mistake where the code does not match the paper, like picture
![21f8e6ba87bfcbd64e0d162d0521679](https://github.com/thuml/Koopa/assets/44513759/fc20dc45-fe57-42dc-b341-39eeeeec38eb)

Therefore, after I fix this bug, my mse and mae decline a little
![image](https://github.com/thuml/Koopa/assets/44513759/684f499e-e94d-4e3b-a375-e4b041205694)

Looking forward to your reply

**Comment by WenWeiTHU** [comment]
Hello, please check this, the multipler as mask essentially selects the complementary set.

<img width="660" alt="图片" src="https://github.com/thuml/Koopa/assets/39073236/1576313e-55bc-426e-89c4-cdf65513aa26">

**Comment by MuliMuri** [comment]
Thanks for your reply
It's my fault : )
