### ISSUE TITLE
关于时间序列非平稳的疑问

### ISSUE THREAD

**Issue by ownnaruto** [thuml/Koopa#18]
您好，我对于时间序列非平稳带来的问题一直存在一些疑惑，时间序列非平稳是指序列的统计信息随时间变化，可是这到底是如何影响神经网络模型的预测呢？神经网络预测输入的是历史序列，输出的是未来序列，只要这个映射关系是存在一定规律的，那么神经网络应该就能够在一定程度上学到这种关系，序列的非平稳是如何影响这种映射关系的呢？为什么平稳的序列就一定更好呢？（白噪声也是一种平稳序列，可是却完全无法预测。

**Comment by WenWeiTHU** [comment]
Hello, please refer to https://github.com/thuml/Nonstationary_Transformers/issues/37
