### ISSUE TITLE
Request for Code and Visualization Operators for "Degree of Variation" Comparison

### ISSUE THREAD

**Issue by 7HZX** [thuml/Koopa#19]
Hello,

I recently came across your paper and was particularly intrigued by the method you've developed for distinguishing between time-variant and time-invariant components in time series data. I am currently working on a related project and found your approach to be potentially beneficial for my research.

Could you kindly share the code and any visualization tools you used to measure and display the "Degree of Variation" for the decomposed components? Access to this code would greatly assist in better understanding your methodology and possibly extending its application.

Thank you for your consideration, and I look forward to possibly collaborating or learning more about your work.

**Comment by lichenyu20** [comment]
Hello, you can calculate Degree of Variation as follows:

1. decompose the series into time-invariant component and time-variant component using Fourier Filter;
1. utilize the two components to train MLPs;
1. calculate the standard deviation of linear weighting.
