### ISSUE TITLE
从第二个epoch开始，每个K都报Encounter K with nan, replace K by identity matrix

### ISSUE THREAD

**Issue by Kalot226** [thuml/Koopa#21]
作者您好，我换了自己的数据集，数据集中没有空值之类的，就是正常的数据集。但是训练的时候，第一个epoch正常，但是从第二个epoch开始，每个K都报Encounter K with nan, replace K by identity matrix，能请教一下为什么吗，每个epoch传入的文件应该都是一样的啊

**Comment by lichenyu20** [comment]
您好，感谢您对我们工作的关注。请问您方便提供数据集吗，我们这边可以测试一下～
