### ISSUE TITLE
About encoder in time-invariant and time-variant KP

### ISSUE THREAD

**Issue by lizlive** [thuml/Koopa#26]
您好，一个关于Koopa的 time-invariant KP实现问题，在文章中你的描述是映入encoder将维度 TxC 转换成D， 但是在code中是一个T转换成 D 的MLP且被C个channel共享，这确实能很大程度的减少参数量，但是不同的channel共享同一个mapping是不是不太合理？对比而言，在time-variant KP中是将 SxC 转换成 D 的。不知道我的理解是否正确，期待您的回答。

**Comment by WenWeiTHU** [comment]
感谢您的关注，其实我们在论文的最后一章讨论了这个问题，您提到的确实是一个很好的改进

<img width="1159" alt="image" src="https://github.com/user-attachments/assets/68b0cb15-a8ac-433a-8a2a-67b2d06df003">
