### ISSUE TITLE
Why does the time-variant Koopman operator predict an extra step?

### ISSUE THREAD

**Issue by Leopold2333** [thuml/Koopa#3]
I'm confused about the code in the model part, that is, `line 74 - line 98` in [models/Koopa.py](https://github.com/thuml/Koopa/blob/main/models/Koopa.py).

Why isn't the variable `z_pred` get from `one_step_forward()` function put into the list `z_preds`?

There is a time interval between variable x and variable y, and the least square method is used to calculate $K_{\mathrm{var}}$ . Next, the value `z_pred` is calculated with the last segment of the look-back window and $K_{\mathrm{var}}$ as input, corresponding to [#L85](https://github.com/thuml/Koopa/blob/main/models/Koopa.py/#L85). This `z_pred` variable seems not belong to the look-back window, but the predicting window. So why isn't this `z_pred` variable in the `z_preds` ?

<img width="809" alt="C70CDA73AB01AEA64D6BEB8F98336274" src="https://github.com/thuml/Koopa/assets/72480342/bccbe036-5f3f-4bff-92a6-01e3c37f7146">

I try to change the code snippets of `line 94 - line 95` to this:
```
        z_preds = []
        z_preds.append(z_pred)
        for i in range(1, pred_len):
```
And the result gets worse, well, that makes me confused.

**Comment by WenWeiTHU** [comment]
Hi, z_pred obtained in `line 93` is the next prediction of Z_back, not the first segment of forecasting.

<img width="536" alt="image" src="https://github.com/thuml/Koopa/assets/39073236/f1672c3c-9de0-4a80-8202-188f86bd0785">

**Comment by Leopold2333** [comment]
> Hi, z_pred obtained in `line 93` is the next prediction of Z_back, not the first segment of forecasting.
> 
> <img alt="image" width="536" src="https://user-images.githubusercontent.com/39073236/282242476-f1672c3c-9de0-4a80-8202-188f86bd0785.png">

But Z_back covers the range from z_1 to z_T/S-1 , while in the code, `z_pred` is calculated with `z[:,-1:]`, which is z_T/S, it's not the element in Z_back.

I try to compare the last element on dim 1 of `y` with `z[:, -1:]`, they are the same.

**Comment by WenWeiTHU** [comment]
Oh, you are right. `one_step_forward` in `KPLayer` needs some fixing.

**Comment by WenWeiTHU** [comment]
Thanks a lot. 

BTW, `one_step_forward` of `KPLayer` is simply a demonstration. In fact, there is no need to apply multiple times of `one_step_forward`, since the obtained `K`s in each iteration are all the same. We actually obtain the results directly by `KPLayerApprox`.

**Comment by Leopold2333** [comment]
Get it, and thanks for your replies! This is a really fantacy work and I really learned a lot from it!
