### ISSUE TITLE
A RuntimeError of "loss.backward()"

### ISSUE THREAD

**Issue by MrTyler2022** [thuml/Koopa#4]
hello,when I run your code,its has a error, when runnging at "loss.backward()", its has a mistake :"RuntimeError: the derivative for 'linalg_lstsq' is not implemented." How to resolve it,can you help me? what's the pytorch version?

**Comment by lichenyu20** [comment]
Hello, please use a version of pytorch>=1.12, closed as https://github.com/thuml/Koopa/issues/1
