### ISSUE TITLE
关于算子是啥的问题

### ISSUE THREAD

**Issue by Lisen-Zhao** [thuml/Koopa#8]
作者你好，请问算子到底是啥，是如何得到的呢？通过查看源码发现时不变部分的算子是可学习参数的SVD的左右奇异矩阵相乘，时变部分的算子是可学习参数的最小二乘法的解，请问为什么是将这两个当成算子？

**Comment by WenWeiTHU** [comment]
您好，感谢关注。算子本身是描述系统转移的向量场（无限维矩阵）。在数据驱动的场景下，可以使用有限维矩阵近似。Koopa计算算子时分别使用了基于数据驱动的方式（可学习参数矩阵，时不变部分）以及局部计算解析解的方式（eDMD算法，时变部分），另参考：

* Deep learning for universal linear embeddings of nonlinear dynamics[J]. Nature communications, 2018, 9(1): 4950.
* DMD：https://en.wikipedia.org/wiki/Dynamic_mode_decomposition.

**Comment by Lisen-Zhao** [comment]
感谢您在百忙之中的及时解答，我的学识有限，还望海涵。
